### ISSUE TITLE
build_pptx : output_file not found

### ISSUE THREAD

**Issue by beatrizmilz** [jhelvy/renderthis#19] opened 2021-03-26 12:20 UTC
Hi @jhelvy ! 
I`m trying to use this package for the first time.
Someone asked me if it was possible to convert a xaringan presentation into pptx. 

I tried to use the function build_pptx() and I keep getting the same error.

Example 1:
``` r
xaringanBuilder::build_pptx("https://jhelvy.github.io/xaringanBuilder/reference/figures/slides.html")
#> ℹ Building slides.pdf from slides.html
#> ✓ Building slides.pdf from slides.html ... done
#> 
#> Error in fs::path_file(output_file): objeto 'output_file' não encontrado
```

<sup>Created on 2021-03-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

The error was "output_file" not found. So I used a name for an output file and got the same error:

``` r
xaringanBuilder::build_pptx(input = "https://jhelvy.github.io/xaringanBuilder/reference/figures/slides.html",
                            output_file = "slides.pptx")
#> ℹ Building slides.pdf from slides.html
#> ✓ Building slides.pdf from slides.html ... done
#> 
#> Error in fs::path_file(output_file): objeto 'output_file' não encontrado
```

<sup>Created on 2021-03-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Do you have any tips of what am I doing wrong? Thank you so much!

Edit: a PDF version was created. But not the pptx.

Edit 2: I do not have the Powerpoint from Microsoft, only LibreOffice. Maybe this is causing the error?

**Comment by jhelvy** [comment] 2021-03-26 13:36
Hmm...when I run that I don't get that error, but the pptx output type uses the [{officer}](https://davidgohel.github.io/officer/) package, which I believe requires you have Microsoft Powerpoint. I might be wrong. But the error message you're getting is definitely confusing, so I can improve that. Might need to run a check for whether you have Powerpoint installed on your machine and throw an error if it's missing.

**Comment by jhelvy** [comment] 2021-03-26 13:45
Okay, so apparently you don't need Microsoft Office installed...the {officer} [DESCRIPTION](https://github.com/davidgohel/officer/blob/master/DESCRIPTION) file says `"The package does not require any installation of Microsoft products to be able to write Microsoft files."`

So there must be something else going on. But I can't reproduce that error. Did you installed the latest version from GitHub? If so, then there's got to be something different between our computers that we'll have to figure out.

**Comment by beatrizmilz** [comment] 2021-03-26 13:53
Thanks for your answer!
I have the package officedown installed.

I asked a friend that haves Microsoft powerpoint installed, and he got the same error. So error is not because of the lack of powerpoint indeed :) 

About the installation, I did install from GitHub today. So I have the most recent version.

Maybe is something related with my OS? I use mac:

``` r
# install.packages("remotes")
# remotes::install_github("jhelvy/xaringanBuilder")
library(xaringanBuilder)
build_pptx("https://jhelvy.github.io/xaringanBuilder/reference/figures/slides.html")
#> ℹ Building slides.pdf from slides.html
#> ✓ Building slides.pdf from slides.html ... done
#> 
#> Error in fs::path_file(output_file): objeto 'output_file' não encontrado

sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-apple-darwin17.0 (64-bit)
#> Running under: macOS Big Sur 10.16
#> 
#> Matrix products: default
#> BLAS:   /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRblas.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/4.0/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] pt_BR.UTF-8/pt_BR.UTF-8/pt_BR.UTF-8/C/pt_BR.UTF-8/pt_BR.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] xaringanBuilder_0.0.7.9001
#> 
#> loaded via a namespace (and not attached):
#>  [1] zip_2.1.1            Rcpp_1.0.6           pillar_1.5.1        
#>  [4] compiler_4.0.3       later_1.1.0.1        highr_0.8           
#>  [7] tools_4.0.3          digest_0.6.27        uuid_0.1-4          
#> [10] jsonlite_1.7.2       evaluate_0.14        lifecycle_1.0.0     
#> [13] tibble_3.1.0         pkgconfig_2.0.3      rlang_0.4.10        
#> [16] reprex_1.0.0         rstudioapi_0.13      cli_2.3.1           
#> [19] yaml_2.2.1           pagedown_0.13        xfun_0.22           
#> [22] fastmap_1.1.0        officer_0.3.16       styler_1.3.2        
#> [25] stringr_1.4.0        knitr_1.31           xml2_1.3.2          
#> [28] fs_1.5.0             vctrs_0.3.6          websocket_1.3.2     
#> [31] chromote_0.0.0.9003  glue_1.4.2           R6_2.5.0            
#> [34] processx_3.5.0       fansi_0.4.2          rmarkdown_2.7.4     
#> [37] servr_0.21           purrr_0.3.4          magrittr_2.0.1      
#> [40] backports_1.2.1      promises_1.2.0.1     ps_1.6.0            
#> [43] ellipsis_0.3.1       htmltools_0.5.1.9000 assertthat_0.2.1    
#> [46] httpuv_1.5.5         utf8_1.2.1           stringi_1.5.3       
#> [49] crayon_1.4.1
```

<sup>Created on 2021-03-26 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>


Edit: another friend that uses Windows said he got the same error... so I think that my guess about the OS is not true.

**Comment by jhelvy** [comment] 2021-03-26 14:01
Hmm...okay this one's a puzzle...I'll try some tests to see if I can get to the bottom. The fact that the pdf is building is even stranger since it doesn't seem like a file path error. Like, it can find the `output_file` name for the pdf but not for the pptx.

**Comment by beatrizmilz** [comment] 2021-03-26 14:24
I cloned the package, and I'm trying to identify in which line I start getting an error (inside the function in the file `pptx.R`)

As soon as I have anything I will let you know :) Thank you so much

**Comment by jhelvy** [comment] 2021-03-26 14:35
Cool. The issue might be somewhere in `utils.R` - there's a `build_paths()` function that is called early on to create a list of all the paths to potential inputs and outputs. So if the error is saying it can't find the output file name, it might be coming from there. I just wish I could get the same error.

**Comment by jhelvy** [comment] 2021-03-26 15:24
Okay, I'm now getting the same error after the last commit. I've changed `magick::image_read()` to `magick::image_read_pdf()` inside `pdf_to_png()`, updated the `density` argument to be a number in the documentation, and  added {pdftools} to imports since it's used in `magick::image_read_pdf()`. Still haven't figured out why we're getting the path problem though. If I `devtools::load_all()`, everything works, but if I install the package, it doesn't.

**Comment by beatrizmilz** [comment] 2021-03-26 15:45
> If I devtools::load_all(), everything works, but if I install the package, it doesn't.

The same happens here!

**Comment by jhelvy** [comment] 2021-03-26 16:19
One step closer - it has something to do with `print_build_status()`. If I comment that line out, everything works.

**Comment by jhelvy** [comment] 2021-03-26 17:52
I think I finally got this fixed now on the latest commit. It was a bug with the glue syntax in the statement in `print_build_status()`...I just switched it to use `paste0()` and now (hopefully) it should work.

**Closed as completed** 2021-03-26 17:51 UTC

**Comment by beatrizmilz** [comment] 2021-03-26 19:30
Just tested here and it works! :D Thank you.
