### ISSUE TITLE
qmd (or html) to pdf failure - Error in force(exp)

### ISSUE THREAD

**Issue by mfarrant** [jhelvy/renderthis#81] opened 2024-09-30 21:03 UTC
When trying to use renderthis 0.2.0, I get:

renderthis::to_pdf("PHAR0006_Intro.html")
✖ Rendering PHAR0006_Intro.html into PHAR0006_Intro.pdf ... failed
Error in force(expr) : 
  Failed to generate output. Reason: Failed to open http://127.0.0.1:7459/favicon.ico (HTTP status code: 404)

What does this mean?

Thanks

**Comment by jhelvy** [comment] 2024-09-30 21:05
I think this is a duplicate of #78 

Solution is [here](https://github.com/jhelvy/renderthis/issues/78#issuecomment-2381272955)

**Closed as completed by jhelvy** 2024-09-30 21:05 UTC

**Comment by mfarrant** [comment] 2024-09-30 21:21
> I think this is a duplicate of #78
> 
> Solution is [here](https://github.com/jhelvy/renderthis/issues/78#issuecomment-2381272955)

Thank you - mostly works but all icons are missing e.g. {{< iconify academicons:moodle size=3x >}}

**Comment by jhelvy** [comment] 2024-09-30 21:26
Darn. But I don't know if that's an issue related to the favicon error. That might just be something else. Perhaps the icon files are not being embedded into the html file? I'm assuming this is a quarto doc, maybe try changing the yaml setting to a [self-contained document](https://quarto.org/docs/output-formats/html-basics.html#self-contained)?

```yaml
---
format:  
  html:    
    embed-resources: true
---
```

**Comment by mfarrant** [comment] 2024-09-30 21:28
Thank you for your help!  I will investigate this... after a night's sleep.

**Comment by mfarrant** [comment] 2024-10-02 14:01
Following up my previous message concerning failure of `renderthis` to work with a Quarto revealjs presentation (`Failed to generate output. Reason: Failed to open http://127.0.0.1:7459/favicon.ico (HTTP status code: 404)`).

 As suggested, installing the `servr` package allows the PDF file to be produced without any error notification. 
 
 BUT in the PDF:

1) iconify icons are not present e.g. `{{< iconify academicons:moodle size=3x >}}`
2) a two column page using `.fragment` is blank (only title is produced)
3) a table that uses `::: r-fit-text` now has single lines of text that run off the right of the page

As a test -- using the identical YAML as for the full (failed) PDF conversion -- while the HTML outputs are all fine, for the `renderthis`-generated PDF: 

1) The two column with .fragment slide now works when run alone as a single slide
2) The table with `::: r-fit-text` still runs off the right as a sinlge slide
3) Combining (1) and (2) in a two-slide presentation now leaves the two-column page empty. 
4) no iconify icons work when present as single slides


Inculding ` embed-resources: true` to make a self-contained HTML file did not fix anything.

Any help would be appreciated as I very much enjoy showing Quarto slides but sometimes really need to share as PDFs.

**Comment by gadenbuie** [comment] 2024-10-02 14:36
The first challenge is to determine if these issues are a problem renderthis, quarto, or pagedown. Compare the results of the following:

1. `renderthis::to_pdf("slides.qmd")`
2. `quarto::render("slides.qmd"); pagedown::chrome_print("slides.html")`
3. Open the rendered slides in Chrome and print to PDF

Please let us know if the output is different in any of these scenarios.

**Comment by mfarrant** [comment] 2024-10-02 17:02
Thanks for the suggestions.
`renderthis::to_pdf("slides.qmd")` and 
`pagedown::chrome_print("slides.html")` of quarto rendered slides produce exactly the same errors. 
Opening the rendered slides in Chrome and printing to PDF is worse in some respects and better in one –
1) Title slide is missing elements and background colour 
2) all slides that should have a background colour (eg `## Abbreviated syllabus {background-color="#43464B"}` are white
3) A two-column slide is spread over two pages
4) Another two-column slide is one continuous column
5) Everything is pushed to the left - nothing entered
6) the `::: r-fit-text` table is still running off the right
7) but the icons all work!

**Comment by gadenbuie** [comment] 2024-10-02 17:17
That's helpful and at least demonstrates that this isn't the result of anything within renderthis' control. The difference between `pagedown::chrome_print()` might be that you're actually using two different browsers. What does `pagedown::find_chrome()` return? That will tell you exactly which browser was used by pagedown.

Anyway, what renderthis does, by way of calling `pagedown::chrome_print()`, is really the programmatic equivalent of opening the slides in the browser and printing to PDF. How the slides are rendered when printed is controlled partly by Quarto and partly by the framework Quarto uses, revealjs. I'd recommend creating small, reproducible examples and reporting the issues upstream to Quarto.

**Comment by mfarrant** [comment] 2024-10-02 17:23
Thanks.
`pagedown::find_chrome()`  returns
 `[1] "/Applications/Google Chrome.app/Contents/MacOS/Google Chrome"`
