### ISSUE TITLE
Error in force(expr) :    Failed to generate output. Reason: Failed to open http://127.0.0.1:7080/favicon.ico (HTTP status code: 404)

### ISSUE THREAD

**Issue by TiagoVentura** [jhelvy/renderthis#78] opened 2024-09-01 02:32 UTC
Hi all, 

I am trying to convert this simple HTML generated with Xaringan to PDF, and I need help with this error. This is a new error since I used to convert HTML using renderthis::to_pdf before, and I never got this error.

This is the xaringan file 

``` 
---
title: "Presentation Ninja"
subtitle: "with xaringan"
author: "Yihui Xie"
date: "2016/12/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      countIncrementalSlides: false
---

One slide.

---

Another slide.
```

Calling renderthis to convert to pdf

```
renderthis::to_pdf("test.rmd")
```

Error

```
Error in force(expr) : 
  Failed to generate output. Reason: Failed to open http://127.0.0.1:7080/favicon.ico (HTTP status code: 404)

```

Any help would be appreciated!

**Comment by jhelvy** [comment] 2024-09-01 03:58
Duplicate of #77. Short story is the source of the problem is in dependencies that have yet to be fixed. #77 shows some work arounds people have found for the time being.

**Closed as completed** 2024-09-01 03:58 UTC

**Comment by jhelvy** [comment] 2024-09-29 09:03
Temporary solution for now that worked for me:

```r
install.packages('servr')
```

See more [here](https://stackoverflow.com/a/78929375/1456821).
